[package]
name = "stock-values"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
yahoo_finance_api = "2.0"
dotenvy = "0.15"
clap = { version = "4.0", features = ["derive"] }
