name: Build Cross-Platform Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            binary-name: stocks-values.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-binary
        path: target/${{ matrix.target }}/release/${{ matrix.binary-name }}